<a href="https://colab.research.google.com/github/vineethajallipalli/Vineetha/blob/main/ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
class Employee:
    employee_count = 0
    total_salary = 0
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        Employee.employee_count += 1
        Employee.total_salary += salary


    @classmethod
    def average_salary(cls):
        if cls.employee_count == 0:
            return 0
        return cls.total_salary / cls.employee_count

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

employee1 = Employee("Rohit", "Mudiam", 90000, "HR")
employee2 = FulltimeEmployee("Vinee", "Jallipalli", 80000, "QA")
employee3 = Employee("Vivek", "Jallipalli", 99000, "Finance")

print(f"Total Employees: {Employee.employee_count}")
print(f"Average Salary: {Employee.average_salary()}")

print(f"Employee1: {employee1.name}, {employee1.family}, {employee1.salary}, {employee1.department}")
print(f"Employee2: {employee2.name}, {employee2.family}, {employee2.salary}, {employee2.department}")
print(f"Employee3: {employee3.name}, {employee3.family}, {employee3.salary}, {employee3.department}")


Total Employees: 3
Average Salary: 89666.66666666667
Employee1: Rohit, Mudiam, 90000, HR
Employee2: Vinee, Jallipalli, 80000, QA
Employee3: Vivek, Jallipalli, 99000, Finance


In [1]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)



Original Random Vector:
 [13.77009152  8.64650775 15.87947129  9.61577928 15.70330823 17.96240109
 15.16096613  8.48586502 16.30355052 18.80931378 11.92710987 15.29181108
 16.89597091 19.8747145  19.48291435 17.6213314  17.88888946  7.77118246
  3.91758188  7.94490517]


In [2]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[13.77009152  8.64650775 15.87947129  9.61577928 15.70330823]
 [17.96240109 15.16096613  8.48586502 16.30355052 18.80931378]
 [11.92710987 15.29181108 16.89597091 19.8747145  19.48291435]
 [17.6213314  17.88888946  7.77118246  3.91758188  7.94490517]]


In [3]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[13.77009152  8.64650775  0.          9.61577928 15.70330823]
 [17.96240109 15.16096613  8.48586502 16.30355052  0.        ]
 [11.92710987 15.29181108 16.89597091  0.         19.48291435]
 [17.6213314   0.          7.77118246  3.91758188  7.94490517]]
